export type QuestionType = 'single' | 'multi' | 'table' | 'text'

export interface Question {
  id: string
  key: string
  label: string
  type: QuestionType
  options?: string[]
  tableRows?: string[]
  tableColumns?: string[]
  category?: string
  applies_to_categories?: string[]
  note?: string
}

export interface Phase {
  id: number
  title: string
  description: string
  questions: Question[]
}

export const PHASES: Phase[] = [
  {
    id: 1,
    title: 'Phase 1: 調理環境',
    description: 'Q1-Q4 — 回答1つで全品に波及',
    questions: [
      {
        id: 'q1a',
        key: 'frying_oil_shared',
        label: 'Q1a. 揚げ物の油は全メニュー同じですか？',
        type: 'single',
        options: ['全部同じ油', '海鮮と肉で分けてる', 'メニューごとに専用', '揚げ物メニューはない', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'tempura', 'side'],
      },
      {
        id: 'q1b',
        key: 'frying_oil_type',
        label: 'Q1b. 油の種類は？',
        type: 'single',
        options: ['キャノーラ油（菜種油）', '大豆油', '米油', 'ラード（動物性）', 'わからない', 'その他'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'tempura', 'side'],
      },
      {
        id: 'q1b2',
        key: 'frying_oil_shellfish',
        label: 'Q1b-2. その油で、えび・かにも揚げますか？',
        type: 'single',
        options: ['はい', 'いいえ（甲殻類だけは別）', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'tempura', 'side'],
      },
      {
        id: 'q1d',
        key: 'peanut_oil',
        label: 'Q1d. 落花生油（ピーナッツオイル）は使ってますか？',
        type: 'single',
        options: ['使ってない', '使ってる', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'tempura', 'side'],
      },
      {
        id: 'q2a',
        key: 'utensil_sharing',
        label: 'Q2a. えび・かにを扱う道具（まな板・包丁・鍋等）は？',
        type: 'single',
        options: ['他の料理と共有してる', '甲殻類専用の道具がある', '特に意識して分けてない', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'sashimi', 'sushi', 'tempura', 'nabe', 'side'],
      },
      {
        id: 'q2b',
        key: 'utensil_wash_timing',
        label: 'Q2b. 洗浄のタイミングは？',
        type: 'single',
        options: ['使うたびに洗う', 'まとめて洗う', '特に決めてない', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'appetizer', 'sashimi', 'sushi', 'tempura', 'nabe', 'side'],
      },
      {
        id: 'q3a',
        key: 'boiling_water_shared',
        label: 'Q3a. 蕎麦とうどんの茹で湯は？',
        type: 'single',
        options: ['同じ鍋で茹でてる', '鍋を分けてる', '蕎麦は外注', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['soba', 'ramen'],
      },
      {
        id: 'q3b',
        key: 'soba_supplier',
        label: 'Q3b. 蕎麦はどこから仕入れてますか？',
        type: 'text',
        category: 'cooking_environment',
        applies_to_categories: ['soba'],
        note: '仕入れ先名',
      },
      {
        id: 'q4a',
        key: 'grill_sharing',
        label: 'Q4a. 炭火焼き・鉄板は、肉と魚で分けてますか？',
        type: 'single',
        options: ['同じグリルで焼いてる', '肉と魚で分けてる', 'メニューごとに違う', 'わからない'],
        category: 'cooking_environment',
        applies_to_categories: ['main', 'yakitori'],
      },
    ],
  },
  {
    id: 2,
    title: 'Phase 2: 調味料・ベース',
    description: 'Q5-Q8 — 数十品に波及',
    questions: [
      {
        id: 'q5a',
        key: 'soy_sauce_type',
        label: 'Q5a. 使ってる醤油はどれですか？',
        type: 'single',
        options: ['普通の醤油（小麦入り）のみ', 'たまり醤油（小麦なし）のみ', '両方使い分けてる', 'わからない'],
        category: 'seasoning',
        applies_to_categories: ['main', 'appetizer', 'sashimi', 'sushi', 'yakitori', 'nabe', 'side'],
      },
      {
        id: 'q5b',
        key: 'tamari_usage',
        label: 'Q5b. たまり醤油を使うのは？（複数OK）',
        type: 'multi',
        options: ['刺身のつけ醤油', '寿司', '焼き鳥のタレ', '煮物', '茶漬け', 'その他'],
        category: 'seasoning',
        applies_to_categories: ['main', 'sashimi', 'sushi', 'yakitori'],
      },
      {
        id: 'q6a',
        key: 'dashi_type',
        label: 'Q6a. メインで使ってる出汁は？（複数OK）',
        type: 'multi',
        options: ['鰹出汁', '昆布出汁', '合わせ出汁（鰹+昆布）', '鶏ガラ', '豚骨', 'あごだし', '化学調味料・顆粒だし', 'わからない'],
        category: 'seasoning',
        applies_to_categories: ['main', 'nabe', 'soup', 'soba', 'ramen'],
      },
      {
        id: 'q6b',
        key: 'dashi_by_dish',
        label: 'Q6b. 料理によって出汁を使い分けてますか？',
        type: 'single',
        options: ['全部同じ', '使い分けてる'],
        category: 'seasoning',
        applies_to_categories: ['main', 'nabe', 'soup', 'soba', 'ramen'],
      },
      {
        id: 'q7a',
        key: 'miso_type',
        label: 'Q7a. 使ってる味噌の種類は？',
        type: 'single',
        options: ['合わせ味噌', '赤味噌', '白味噌', '複数使い分け', 'わからない'],
        category: 'seasoning',
        applies_to_categories: ['main', 'nabe', 'soup'],
      },
      {
        id: 'q7b',
        key: 'miso_dashi_included',
        label: 'Q7b. 味噌にだし入りのものを使ってますか？',
        type: 'single',
        options: ['だし入り味噌を使ってる', 'だしなし（別で出汁をとってる）', 'わからない'],
        category: 'seasoning',
        applies_to_categories: ['main', 'nabe', 'soup'],
      },
      {
        id: 'q8a',
        key: 'dressing_type',
        label: 'Q8a. ドレッシングやソースは自家製ですか？既製品ですか？',
        type: 'single',
        options: ['ほぼ自家製', 'ほぼ既製品', 'ものによる', 'わからない'],
        category: 'seasoning',
        applies_to_categories: ['salad', 'main', 'side'],
      },
      {
        id: 'q8b',
        key: 'caesar_ingredients',
        label: 'Q8b. シーザードレッシングに入ってるものは？（複数OK）',
        type: 'multi',
        options: ['マヨネーズ', '卵黄', 'アンチョビ（魚介）', 'パルメザンチーズ', 'にんにく', 'わからない', 'その他'],
        category: 'seasoning',
        applies_to_categories: ['salad'],
      },
    ],
  },
  {
    id: 3,
    title: 'Phase 3: 特定原材料8品目',
    description: 'Q9-Q16 — 表示義務のある8品目',
    questions: [
      {
        id: 'q9a',
        key: 'shrimp_hidden',
        label: 'Q9a. えびを直接使う料理以外で、えびを使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'tempura', 'sashimi'],
        note: '料理名',
      },
      {
        id: 'q9b',
        key: 'shrimp_in_tempura',
        label: 'Q9b. 天婦羅5種盛りにえびは入りますか？',
        type: 'single',
        options: ['必ず入る', '日によって変わる', '入らない'],
        category: 'allergen_8',
        applies_to_categories: ['tempura'],
      },
      {
        id: 'q9c',
        key: 'shrimp_in_sashimi',
        label: 'Q9c. 刺身盛り合わせにえびは入りますか？',
        type: 'single',
        options: ['必ず入る', '日によって変わる', '入らない'],
        category: 'allergen_8',
        applies_to_categories: ['sashimi'],
      },
      {
        id: 'q10a',
        key: 'crab_hidden',
        label: 'Q10a. かにを直接使う料理以外で、かにを使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'nabe'],
        note: '料理名',
      },
      {
        id: 'q10b',
        key: 'crab_extract',
        label: 'Q10b. かに味噌やかにエキスを使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'nabe'],
        note: '料理名',
      },
      {
        id: 'q11a',
        key: 'wheat_batter',
        label: 'Q11a. 天婦羅・唐揚げの衣は小麦粉ですか？',
        type: 'single',
        options: ['全部小麦粉', '一部片栗粉', '全部片栗粉', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'tempura'],
        note: '片栗粉のメニュー名',
      },
      {
        id: 'q11b',
        key: 'breadcrumb_usage',
        label: 'Q11b. パン粉を使うメニューは？（複数OK）',
        type: 'multi',
        options: ['黒毛和牛レアカツ', '他にもある', 'パン粉は使ってない'],
        category: 'allergen_8',
        applies_to_categories: ['main'],
      },
      {
        id: 'q11c',
        key: 'pinpin_batter',
        label: 'Q11c. ピンピン焼きの生地は？',
        type: 'single',
        options: ['小麦粉ベース', '片栗粉ベース', 'ミックス', 'その他'],
        category: 'allergen_8',
        applies_to_categories: ['main'],
      },
      {
        id: 'q12a',
        key: 'soba_flour_hidden',
        label: 'Q12a. 蕎麦以外でそば粉を使うメニューはありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['soba', 'main'],
        note: '料理名',
      },
      {
        id: 'q13a',
        key: 'egg_state',
        label: 'Q13a. 以下の料理、卵の状態は？',
        type: 'table',
        tableRows: ['黄身のせサーモンユッケ', '黒毛和牛ユッケ(タレ)', '月見とろろ蕎麦', 'かき卵うどん', '温玉シーザーサラダ', 'もつすき（卵つけダレ）', 'つくね（つなぎ）'],
        tableColumns: ['生', '半熟', '加熱', '卵不使用'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'sashimi', 'soba', 'ramen', 'salad', 'nabe', 'yakitori'],
      },
      {
        id: 'q13b',
        key: 'mayo_type',
        label: 'Q13b. マヨネーズは市販品ですか？自家製ですか？',
        type: 'single',
        options: ['市販品（キューピー等）', '自家製', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'salad'],
      },
      {
        id: 'q13c',
        key: 'tempura_egg',
        label: 'Q13c. 天婦羅の衣に卵を使ってますか？',
        type: 'single',
        options: ['使ってる', '使ってない（水と小麦粉のみ）', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['tempura'],
      },
      {
        id: 'q13d',
        key: 'egg_hidden',
        label: 'Q13d. 上記以外で卵を使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'dessert'],
        note: '料理名',
      },
      {
        id: 'q14a',
        key: 'dairy_hidden',
        label: 'Q14a. バター・クリーム・チーズの隠れ使用はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'dessert', 'bread'],
        note: '料理名',
      },
      {
        id: 'q14b',
        key: 'soy_ice_dairy',
        label: 'Q14b. 豆乳アイスプリンに牛乳・生クリームは？',
        type: 'single',
        options: ['入ってない（豆乳のみ）', '少し入ってる', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['dessert'],
      },
      {
        id: 'q14c',
        key: 'habutae_ice_dairy',
        label: 'Q14c. 羽二重アイス最中のアイスは？',
        type: 'single',
        options: ['乳製品入り（普通のアイス）', '豆乳・植物性ベース', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['dessert'],
      },
      {
        id: 'q15a',
        key: 'peanut_usage',
        label: 'Q15a. 落花生（ピーナッツ）を使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'appetizer', 'dessert'],
        note: '料理名',
      },
      {
        id: 'q16a',
        key: 'walnut_usage',
        label: 'Q16a. くるみを使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['main', 'dessert', 'salad'],
        note: '料理名',
      },
      {
        id: 'q16b',
        key: 'walnut_salad_topping',
        label: 'Q16b. サラダのトッピング等に入る可能性は？',
        type: 'single',
        options: ['ない', '時期やメニューによってはある', 'わからない'],
        category: 'allergen_8',
        applies_to_categories: ['salad'],
      },
    ],
  },
  {
    id: 4,
    title: 'Phase 4: 推奨表示品目',
    description: 'Q17-Q21 — アレルギー事故が多い品目',
    questions: [
      {
        id: 'q17a',
        key: 'nuts_usage',
        label: 'Q17a. アーモンド・カシューナッツ等を使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_recommended',
        applies_to_categories: ['main', 'dessert', 'salad'],
        note: '料理名',
      },
      {
        id: 'q17b',
        key: 'nuts_dessert_topping',
        label: 'Q17b. デザートのトッピングにナッツ類は？',
        type: 'single',
        options: ['ない', 'ある', 'わからない'],
        category: 'allergen_recommended',
        applies_to_categories: ['dessert'],
        note: '料理名',
      },
      {
        id: 'q18a',
        key: 'sesame_usage',
        label: 'Q18a. ゴマ魚以外で、ごまを使う料理はありますか？（複数OK）',
        type: 'multi',
        options: ['ドレッシングに入ってる', '焼き鳥のタレに入ってる', '和え物に使ってる', 'ごま油だけ（粒ごまは使わない）', '他にもある', 'ゴマ魚だけ'],
        category: 'allergen_recommended',
        applies_to_categories: ['main', 'salad', 'yakitori', 'appetizer'],
      },
      {
        id: 'q18b',
        key: 'sesame_fish_type',
        label: 'Q18b. ゴマ魚のゴマは？',
        type: 'single',
        options: ['すりゴマ', 'いりゴマ', '練りゴマ', '複数'],
        category: 'allergen_recommended',
        applies_to_categories: ['main'],
      },
      {
        id: 'q19a',
        key: 'yam_hidden',
        label: 'Q19a. とろろ・山芋・長芋を使う料理は上記2品以外にありますか？',
        type: 'single',
        options: ['ない', 'ある', 'お好み焼き風ピンピン焼きに入ってる', 'わからない'],
        category: 'allergen_recommended',
        applies_to_categories: ['main', 'soba'],
        note: '料理名',
      },
      {
        id: 'q20a',
        key: 'gelatin_usage',
        label: 'Q20a. デザートにゼラチンを使ってますか？',
        type: 'single',
        options: ['使ってる', '使ってない（寒天等を使用）', 'わからない'],
        category: 'allergen_recommended',
        applies_to_categories: ['dessert'],
        note: '料理名',
      },
      {
        id: 'q21a',
        key: 'squid_usage',
        label: 'Q21a. いかを使う料理はありますか？',
        type: 'single',
        options: ['ない', 'ある'],
        category: 'allergen_recommended',
        applies_to_categories: ['main', 'sashimi', 'tempura'],
        note: '料理名',
      },
      {
        id: 'q21b',
        key: 'squid_in_sashimi',
        label: 'Q21b. 刺身盛り合わせにいかは入りますか？',
        type: 'single',
        options: ['必ず入る', '日によって変わる', '入らない'],
        category: 'allergen_recommended',
        applies_to_categories: ['sashimi'],
      },
      {
        id: 'q21c',
        key: 'squid_in_tempura',
        label: 'Q21c. 天婦羅5種盛りにいかは入りますか？',
        type: 'single',
        options: ['必ず入る', '日によって変わる', '入らない'],
        category: 'allergen_recommended',
        applies_to_categories: ['tempura'],
      },
    ],
  },
  {
    id: 5,
    title: 'Phase 5: 個別メニュー確認',
    description: 'Q22-Q28 — Aランク品の詳細確認',
    questions: [
      {
        id: 'q22a',
        key: 'pinpin_variety',
        label: 'Q22a. ピンピン焼き4種類の違いは？',
        type: 'single',
        options: ['ベースの生地は同じ、トッピングが違うだけ', '生地自体も違う'],
        category: 'individual_menu',
        applies_to_categories: ['main'],
        note: '違いの詳細',
      },
      {
        id: 'q22b',
        key: 'pinpin_ingredients',
        label: 'Q22b. 生地の主な原材料は？（複数OK）',
        type: 'multi',
        options: ['小麦粉', '片栗粉', '卵', '山芋', '牛乳', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main'],
      },
      {
        id: 'q23a',
        key: 'course_allergens',
        label: 'Q23a. 各コースに必ず入るアレルゲン食材は？',
        type: 'table',
        tableRows: ['越前カニ堪能 ¥25,000', '極ぼんた ¥6,000', '魚沖 ¥4,000', '博多もつ鍋 ¥3,000', '宴会 ¥2,800'],
        tableColumns: ['えび・かに', '小麦', '卵', '乳', 'そば'],
        category: 'individual_menu',
        applies_to_categories: ['course'],
      },
      {
        id: 'q23b',
        key: 'course_seasonal',
        label: 'Q23b. コース内容は季節で変わりますか？',
        type: 'single',
        options: ['固定（通年同じ）', '季節で一部入れ替え', '毎回違う（おまかせ）'],
        category: 'individual_menu',
        applies_to_categories: ['course'],
        note: '変わる内容',
      },
      {
        id: 'q23c',
        key: 'course_allergy_response',
        label: 'Q23c. コースでアレルギー対応はしてますか？',
        type: 'single',
        options: ['事前に言ってもらえれば対応する', '対応していない', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['course'],
        note: '詳細',
      },
      {
        id: 'q24a',
        key: 'winter_period',
        label: 'Q24a. 冬限定メニューの提供期間は？',
        type: 'single',
        options: ['11月〜2月', '11月〜3月', '品によって違う', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main', 'nabe'],
        note: '詳細',
      },
      {
        id: 'q24b',
        key: 'shirako_type',
        label: 'Q24b. 白子の種類は？',
        type: 'single',
        options: ['真鱈の白子', '河豚の白子', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main', 'sashimi'],
      },
      {
        id: 'q24c',
        key: 'seiko_crab_period',
        label: 'Q24c. セイコ蟹はいつまで？',
        type: 'single',
        options: ['解禁期間のみ（11月〜12月末）', '冷凍ストックで冬の間ずっと', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main'],
      },
      {
        id: 'q25a',
        key: 'motsu_dashi',
        label: 'Q25a. もつ鍋 各味の出汁ベースは？',
        type: 'table',
        tableRows: ['醤油', '味噌', '塩'],
        tableColumns: ['鰹', '鶏ガラ', '豚骨', '昆布', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['nabe'],
      },
      {
        id: 'q25b',
        key: 'motsu_origin',
        label: 'Q25b. ホルモンの種類と産地は？',
        type: 'single',
        options: ['国産', '輸入', '仕入れで変わる', 'わからない'],
        category: 'individual_menu',
        applies_to_categories: ['nabe'],
        note: '産地の詳細',
      },
      {
        id: 'q25c',
        key: 'motsu_ingredients',
        label: 'Q25c. もつ鍋の具材にニラ以外で何が入りますか？（複数OK）',
        type: 'multi',
        options: ['キャベツ', '豆腐', 'もやし', 'にんにく', 'ごま', '唐辛子', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['nabe'],
      },
      {
        id: 'q26a',
        key: 'brulee_ingredients',
        label: 'Q26a. レアチーズアイスブリュレの原材料は？（複数OK）',
        type: 'multi',
        options: ['クリームチーズ', '生クリーム', '卵', '砂糖', '小麦（土台）', 'ゼラチン', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['dessert'],
      },
      {
        id: 'q26b',
        key: 'surprise_dessert',
        label: 'Q26b. サプライズデザート盛り合わせの中身は？',
        type: 'single',
        options: ['固定（いつも同じ）', '日によって変わる'],
        category: 'individual_menu',
        applies_to_categories: ['dessert'],
        note: '内容',
      },
      {
        id: 'q26c',
        key: 'choco_cake_ingredients',
        label: 'Q26c. ぼんた特製チョコケーキの原材料は？（複数OK）',
        type: 'multi',
        options: ['チョコレート（乳含む）', '小麦粉', '卵', 'バター', '生クリーム', 'ナッツ類', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['dessert'],
      },
      {
        id: 'q27a',
        key: 'wagyu_origin',
        label: 'Q27a. 和牛の産地は？',
        type: 'single',
        options: ['福井県産', '他県産', '仕入れ状況で変わる', 'わからない'],
        category: 'individual_menu',
        applies_to_categories: ['main'],
        note: '産地名',
      },
      {
        id: 'q27b',
        key: 'rare_katsu_batter',
        label: 'Q27b. レアカツの衣は？',
        type: 'single',
        options: ['小麦粉 + パン粉', '小麦粉 + 片栗粉', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main'],
      },
      {
        id: 'q27c',
        key: 'yukke_sauce',
        label: 'Q27c. ユッケのタレに入ってるものは？（複数OK）',
        type: 'multi',
        options: ['卵黄（生）', 'ごま油', '醤油', 'コチュジャン', 'にんにく', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['main', 'sashimi'],
      },
      {
        id: 'q28a',
        key: 'sashimi_assort',
        label: 'Q28a. 刺身盛り合わせ、通常どんなネタが入りますか？（複数OK）',
        type: 'multi',
        options: ['まぐろ', 'サーモン', 'ぶり/はまち', '甘海老', 'いか', 'たこ', '白身魚', '貝類', '日によって全然違う', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['sashimi'],
      },
      {
        id: 'q28b',
        key: 'tempura_assort',
        label: 'Q28b. 天婦羅5種盛り、通常どんなネタが入りますか？（複数OK）',
        type: 'multi',
        options: ['えび', 'いか', '白身魚', 'なす', 'さつまいも', 'しいたけ', '大葉', '日によって変わる', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['tempura'],
      },
      {
        id: 'q28c',
        key: 'yakitori_assort',
        label: 'Q28c. 焼き鳥盛り合わせ（5本）、通常どの部位が入りますか？（複数OK）',
        type: 'multi',
        options: ['もも', 'つくね', '砂肝', '皮', 'ハラミ', 'ねぎま', '日によって変わる', 'その他'],
        category: 'individual_menu',
        applies_to_categories: ['yakitori'],
      },
    ],
  },
  {
    id: 6,
    title: 'Phase 6: お店の強み',
    description: 'Q29-Q31 — narrative用',
    questions: [
      {
        id: 'q29a',
        key: 'popular_top3',
        label: 'Q29. 一番出る料理ベスト3は？',
        type: 'text',
        category: 'store_strength',
        applies_to_categories: ['main'],
        note: '1位、2位、3位',
      },
      {
        id: 'q29b',
        key: 'chef_recommend',
        label: 'Q29. 店長が自信ある料理は？',
        type: 'text',
        category: 'store_strength',
        applies_to_categories: ['main'],
      },
      {
        id: 'q30a',
        key: 'fish_source',
        label: 'Q30. 魚の仕入れは？',
        type: 'single',
        options: ['福井港から直送', '市場経由', '業者から仕入れ', 'その他'],
        category: 'store_strength',
        applies_to_categories: ['sashimi', 'sushi', 'main'],
        note: '仕入れ先の詳細',
      },
      {
        id: 'q30b',
        key: 'charcoal_type',
        label: 'Q30. 炭火焼きの炭は？',
        type: 'single',
        options: ['備長炭', 'オガ炭', 'その他', 'わからない'],
        category: 'store_strength',
        applies_to_categories: ['yakitori', 'main'],
      },
      {
        id: 'q30c',
        key: 'vinegar_source',
        label: 'Q30. 赤酢飯（海鮮重）の酢はどこの？',
        type: 'text',
        category: 'store_strength',
        applies_to_categories: ['sushi', 'rice'],
      },
      {
        id: 'q31a',
        key: 'store_uniqueness',
        label: 'Q31. お店が他の居酒屋と一番違うところは？',
        type: 'text',
        category: 'store_strength',
      },
      {
        id: 'q31b',
        key: 'local_ingredient',
        label: 'Q31. 福井の食材で特にこだわってるものは？',
        type: 'text',
        category: 'store_strength',
      },
    ],
  },
]
